name: Setup
description: Setup the environment for the project
runs:
  using: 'composite'
  steps:
    - name: Set up Python and Ansible
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible sshpass

    - name: Set up Bun
      shell: bash
      run: |
        curl -fsSL https://bun.sh/install | bash
        echo "$HOME/.bun/bin" >> $GITHUB_PATH

    - name: Restore environment files from secrets
      shell: bash
      run: |
        echo "${{ secrets.BASE_ENV }}" > .env
        echo "${{ secrets.PROD_ENV }}" > .env.production
        echo "${{ secrets.ANSIBLE_ENV }}" > ansible/playbooks/env.yaml
        cat <<EOF > prompt.md
        ${{ secrets.PROMPT }}
        EOF

    - name: Add SSH private key
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE }}" > ~/.ssh/id_ed25519
        echo "${{ secrets.SSH_PUBLIC }}" > ~/.ssh/id_ed25519.pub
        chmod 600 ~/.ssh/id_ed25519
        chmod 644 ~/.ssh/id_ed25519.pub
        ssh-keyscan -H -p 2222 ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
