name: Setup
description: Setup the environment for the project

inputs:
  base-env:
    description: The base environment file
    required: true
  prod-env:
    description: The production environment file
    required: true
  ansible-env:
    description: The ansible environment file
    required: true
  prompt:
    description: The prompt
    required: true
  ssh-private:
    description: The SSH private key
    required: true
  ssh-public:
    description: The SSH public key
    required: true
  server-host:
    description: The server host
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Python and Ansible
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible sshpass

    - name: Set up Bun
      shell: bash
      run: |
        curl -fsSL https://bun.sh/install | bash
        echo "$HOME/.bun/bin" >> $GITHUB_PATH

    - name: Restore environment files from secrets
      shell: bash
      run: |
        echo "${{ inputs.base-env }}" > .env
        echo "${{ inputs.prod-env }}" > .env.production
        echo "${{ inputs.ansible-env }}" > ansible/playbooks/env.yaml
        cat <<EOF > prompt.md
        ${{ inputs.prompt }}
        EOF

    - name: Add SSH private key
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo "${{ inputs.ssh-private }}" > ~/.ssh/id_ed25519
        echo "${{ inputs.ssh-public }}" > ~/.ssh/id_ed25519.pub
        chmod 600 ~/.ssh/id_ed25519
        chmod 644 ~/.ssh/id_ed25519.pub
        ssh-keyscan -H -p 2222 ${{ inputs.server-host }} >> ~/.ssh/known_hosts
