services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    develop:
      watch:
        - action: sync+restart
          path: ./packages
          target: /app/packages
    image: aybykovskii/daylik-base:latest

  server:
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    develop:
      watch:
        - action: sync+restart
          path: ./apps/server
          target: /app/apps/server
    env_file:
      - .env
    ports:
      - '8080:${SERVER_PORT}'
    networks:
      - daylik
    depends_on:
      base:
        condition: service_started
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://localhost:${SERVER_PORT}/health' ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - ./packages/shared/logger/logs/server:/app/packages/shared/logger/logs/server

  telegram_bot:
    build:
      context: .
      dockerfile: ./apps/telegramBot/Dockerfile
    depends_on:
      base:
        condition: service_started
      server:
        condition: service_healthy
    develop:
      watch:
        - action: sync+restart
          path: ./apps/telegramBot
          target: /app/apps/telegramBot
    env_file:
      - .env
    ports:
      - '3030:${BOT_PORT}'
    networks:
      - daylik
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://localhost:${BOT_PORT}/health' ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - ./packages/shared/logger/logs/bot:/app/packages/shared/logger/logs/bot

  miniapp:
    build:
      context: .
      dockerfile: ./apps/miniapp/Dockerfile
    depends_on:
      base:
        condition: service_started
      server:
        condition: service_healthy
    develop:
      watch:
        - action: sync+restart
          path: ./apps/miniapp
          target: /app/apps/miniapp
    env_file:
      - .env
    ports:
      - '3000:${MINI_APP_PORT}'
    networks:
      - daylik
    volumes:
      - ./packages/shared/logger/logs/miniapp:/app/packages/shared/logger/logs/miniapp

networks:
  daylik:
    external: true
