services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    networks:
      - daylik
    volumes:
      - postgres_data:/var/lib/postgresql/data/:rw
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}' ]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - '5050:80'
    networks:
      - daylik
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin-data:


networks:
  daylik:
    external: true
