services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    develop:
      watch:
        - action: sync+restart
          path: ./packages
          target: /app/packages
    image: aybykovskii/daylik-base:latest

  server:
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    develop:
      watch:
        - action: sync+restart
          path: ./apps/server
          target: /app/apps/server
    env_file:
      - .env
    ports:
      - '8080:${SERVER_PORT}'
    networks:
      - daylik
    depends_on:
      base:
        condition: service_started
    volumes:
      - ./packages/shared/logger/logs/server:/app/packages/shared/logger/logs/server

networks:
  daylik:
    external: true
