services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./templates:/etc/nginx/templates
      - "./static:/usr/share/nginx/html"
      - /etc/letsencrypt:/etc/letsencrypt
    env_file:
      - .env
    ports:
      - '80:80'
      - '443:443'
    networks:
      - daylik

networks:
  daylik:
    external: true
