name: daylik

x-defaults: &defaults
  env_file:
    - .env
  networks:
    - daylik

services:
  postgres:
    <<: *defaults
    image: postgres:latest
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/:rw
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    <<: *defaults
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - '5050:5050'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres_data:
    name: daylik_db_volume
  pgadmin-data:
    name: daylik_pgadmin_volume
networks:
  daylik:
    external: true
