FROM oven/bun:slim

WORKDIR /app

RUN apt-get update && apt-get install -y curl

COPY package.json ./
COPY apps/server/package.json ./apps/server/
COPY apps/telegramBot/package.json ./apps/telegramBot/
COPY apps/miniapp/package.json ./apps/miniapp/
COPY packages/api/package.json ./packages/api/
COPY packages/shared/package.json ./packages/shared/
COPY bun.lock ./
COPY tsconfig.json ./

RUN bun install --frozen-lockfile --verbose

COPY .env ./
COPY .env ./packages/shared/
