- name: Инициализация сервера
  hosts: all_servers

- import_playbook: ./add-user.yaml
- import_playbook: ./install-packages.yaml
- import_playbook: ./update-certificates.yaml
- import_playbook: ./update-docker.yaml