- name: Генерация SSL сертификатов
  hosts: servers
  become: true
  vars_files:
    - env.yaml
  vars:
    domains:
      - daylik.fun
      - bot.telegram.daylik.fun
      - admin.daylik.fun
    repo_path: "/home/{{ user }}/{{ github_repo }}"
    docker_compose_apps_path: "{{ repo_path }}/docker-compose.production.yml"

  tasks:
    - name: Проверка наличия необходимых пакетов
      apt:
        name: certbot
        state: present

    - name: Генерация ssl сертификатов
      command: sudo certbot certonly --standalone -d {{ item }} --email {{ email }} --agree-tos --keep-until-expiring
      loop: "{{ domains }}"

    - name: Добавления хука автогенерации сертификата
      command: sudo /usr/bin/certbot renew
