servers:
  hosts:
    kz:
      ansible_host: 31.130.152.50
      ansible_user: root
      ansible_port: 2222

all_servers:
  children:
    servers:

all:
  vars:
    ansible_ssh_pipelining: true
    ansible_ssh_transfer_method: piped
    ansible_ssh_args: -o ControlMaster=auto -o ControlPersist=15m
