name: Update Certificates

on:
  workflow_dispatch:

jobs:
  update-certificates:
    name: Update Certificates via Ansible
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run Playbook
        uses: ./.github/actions/run-playbook
        with:
          playbook: 'update-certificates'

      - name: Cleanup
        uses: ./.github/actions/cleanup
