name: Update Nginx

on:
  workflow_dispatch:

jobs:
  update-nginx:
    name: Update Nginx via Ansible
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          base-env: ${{ secrets.BASE_ENV }}
          prod-env: ${{ secrets.PROD_ENV }}
          ansible-env: ${{ secrets.ANSIBLE_ENV }}
          prompt: ${{ secrets.PROMPT }}
          ssh-private: ${{ secrets.SSH_PRIVATE }}
          ssh-public: ${{ secrets.SSH_PUBLIC }}
          server-host: ${{ secrets.SERVER_HOST }}

      - name: Run Playbook
        uses: ./.github/actions/run-playbook
        with:
          playbook: 'update-nginx'

      - name: Cleanup
        uses: ./.github/actions/cleanup
