name: Update Nginx

on:
  workflow_dispatch:

jobs:
  update-nginx:
    name: Update Nginx via Ansible
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run Playbook
        uses: ./.github/actions/run-playbook
        with:
          playbook: 'update-nginx'

      - name: Cleanup
        uses: ./.github/actions/cleanup
