name: Update Nginx

on:
  workflow_dispatch:

jobs:
  update-nginx:
    name: Update Nginx via Ansible
    runs-on: ubuntu-latest

    steps:
      - name: Run Workflow
        uses: ./.github/actions/run-workflow
        with:
          workflow: 'ansible:update-nginx'
