name: Update Fail2ban

on:
  workflow_dispatch:

jobs:
  update-fail2ban:
    name: Update Fail2ban via Ansible
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run Playbook
        uses: ./.github/actions/run-playbook
        with:
          playbook: 'update-fail2ban'

      - name: Cleanup
        uses: ./.github/actions/cleanup
